import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: '序卷 · 时间的共轭',
      items: [
        'c01',
        'c02',
        'c03',
        'c04',
        'c05',
      ],
    },
    {
      type: 'category',
      label: '附录',
      items: [
        {
          type: 'autogenerated',
          dirName: 'knowledge',
        },
      ],
    },
  ],
};

export default sidebars;
